//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTS.W._150501.Models.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS.W._150501.Models.Resources.Strings.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string ADM_LOGIN_00001 {
            get {
                return ResourceManager.GetString("ADM_LOGIN_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string ADM_LOGIN_00002 {
            get {
                return ResourceManager.GetString("ADM_LOGIN_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string ADM_MA_ITEMS_00001 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string ADM_MA_ITEMS_00002 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string ADM_MA_ITEMS_00003 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tìm kiếm.
        /// </summary>
        internal static string ADM_MA_ITEMS_00004 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên liên kết.
        /// </summary>
        internal static string ADM_MA_ITEMS_00005 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        internal static string ADM_MA_ITEMS_00006 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh sản phẩm.
        /// </summary>
        internal static string ADM_MA_ITEMS_00007 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string ADM_MA_ITEMS_00008 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        internal static string ADM_MA_ITEMS_00009 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên bản.
        /// </summary>
        internal static string ADM_MA_ITEMS_00010 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string ADM_MA_ITEMS_00011 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string ADM_MA_ITEMS_00012 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng.
        /// </summary>
        internal static string ADM_MA_ITEMS_00013 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách ngôn ngữ.
        /// </summary>
        internal static string ADM_MA_ITEMS_00014 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        internal static string ADM_MA_ITEMS_00015 {
            get {
                return ResourceManager.GetString("ADM_MA_ITEMS_00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string ADM_USERS_PROFILE_00001 {
            get {
                return ResourceManager.GetString("ADM_USERS_PROFILE_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string ADM_USERS_PROFILE_00002 {
            get {
                return ResourceManager.GetString("ADM_USERS_PROFILE_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ khách hàng.
        /// </summary>
        internal static string CLN_CONTACT_00001 {
            get {
                return ResourceManager.GetString("CLN_CONTACT_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch tư vấn.
        /// </summary>
        internal static string CLN_ITEMDETAIL_00001 {
            get {
                return ResourceManager.GetString("CLN_ITEMDETAIL_00001", resourceCulture);
            }
        }
    }
}
