//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối đến máy chủ thất bại..
        /// </summary>
        internal static string CLN_ALERT_ERROR {
            get {
                return ResourceManager.GetString("CLN_ALERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đã được gởi đi.Chúng tôi sẽ liên hệ với quý khách trong thời gian sớm nhất.
        /// </summary>
        internal static string CLN_ALERT_SUCCESS {
            get {
                return ResourceManager.GetString("CLN_ALERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại thông tin.
        /// </summary>
        internal static string CLN_BTN_RESER {
            get {
                return ResourceManager.GetString("CLN_BTN_RESER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gởi thông tin.
        /// </summary>
        internal static string CLN_BTN_SUBMIT {
            get {
                return ResourceManager.GetString("CLN_BTN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string CLN_MASTER_ABOUTUS {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /vi/gioi-thieu.
        /// </summary>
        internal static string CLN_MASTER_ABOUTUS_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUTUS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu về Bệnh viện thẩm mỹ Ngọc Phú.
        /// </summary>
        internal static string CLN_MASTER_ABOUTUS_TITLE {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUTUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 1.
        /// </summary>
        internal static string CLN_MASTER_ADDRESS_1 {
            get {
                return ResourceManager.GetString("CLN_MASTER_ADDRESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ 2.
        /// </summary>
        internal static string CLN_MASTER_ADDRESS_2 {
            get {
                return ResourceManager.GetString("CLN_MASTER_ADDRESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string CLN_MASTER_CONTACTUS {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /vi/lien-he.
        /// </summary>
        internal static string CLN_MASTER_CONTACTUS_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACTUS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        internal static string CLN_MASTER_CONTACTUS_TITLE {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACTUS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền © 2015 {0}..
        /// </summary>
        internal static string CLN_MASTER_COPYRIGHT {
            get {
                return ResourceManager.GetString("CLN_MASTER_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CLN_MASTER_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("CLN_MASTER_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string CLN_MASTER_HOMEPAGE {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /vi/trang-chu.
        /// </summary>
        internal static string CLN_MASTER_HOMEPAGE_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOMEPAGE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch tư vấn.
        /// </summary>
        internal static string CLN_MASTER_ITEMDETAIL_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("CLN_MASTER_ITEMDETAIL_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string CLN_MASTER_MAIL_DES {
            get {
                return ResourceManager.GetString("CLN_MASTER_MAIL_DES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CLN_MASTER_MAIL_EMAIL {
            get {
                return ResourceManager.GetString("CLN_MASTER_MAIL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        internal static string CLN_MASTER_MAIL_NAME {
            get {
                return ResourceManager.GetString("CLN_MASTER_MAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string CLN_MASTER_MAIL_PHONE {
            get {
                return ResourceManager.GetString("CLN_MASTER_MAIL_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string CLN_MASTER_MENU_MOBI_NAME {
            get {
                return ResourceManager.GetString("CLN_MASTER_MENU_MOBI_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string CLN_MASTER_PHONE {
            get {
                return ResourceManager.GetString("CLN_MASTER_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string CLN_MASTER_WEBSITE {
            get {
                return ResourceManager.GetString("CLN_MASTER_WEBSITE", resourceCulture);
            }
        }
    }
}
